"""add agents table

Revision ID: 06647c3c9e10
Revises: f05e6e98e85c
Create Date: 2026-04-20 22:03:09.060731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06647c3c9e10'
down_revision: Union[str, Sequence[str], None] = 'f05e6e98e85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'DISABLED', 'DECOMMISSIONED', name='agent_status'), nullable=False),
    sa.Column('os', sa.Enum('WINDOWS', 'LINUX', 'MACOS', name='agent_os'), nullable=False),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrollment_token_hash', sa.String(length=64), nullable=True),
    sa.Column('enrollment_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index('ix_agents_enrollment_token_hash', 'agents', ['enrollment_token_hash'], unique=False)
    op.create_index('ix_agents_status', 'agents', ['status'], unique=False)
    op.create_index('uq_agents_hostname_active', 'agents', ['hostname'], unique=True, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_agents_hostname_active', table_name='agents', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_agents_status', table_name='agents')
    op.drop_index('ix_agents_enrollment_token_hash', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
