"""add avatar_url to admins and delete avatar from refresh_tokens

Revision ID: 097b6fc1a2e3
Revises: 2cadf3f47ad5
Create Date: 2026-04-19 22:15:42.718454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097b6fc1a2e3'
down_revision: Union[str, Sequence[str], None] = '2cadf3f47ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('avatar_url', sa.String(length=2048), nullable=True))
    op.drop_column('refresh_tokens', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('avatar_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('admins', 'avatar_url')
    # ### end Alembic commands ###
