"""add avatar_url to admins

Revision ID: 2cadf3f47ad5
Revises: 5890732483fd
Create Date: 2026-04-19 21:55:08.752419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cadf3f47ad5'
down_revision: Union[str, Sequence[str], None] = '5890732483fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('avatar_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'avatar_url')
    # ### end Alembic commands ###
