"""add groups and agent_group_memberships

Revision ID: bb6189232cb8
Revises: 06647c3c9e10
Create Date: 2026-04-20 22:32:14.291679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6189232cb8'
down_revision: Union[str, Sequence[str], None] = '06647c3c9e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_index('uq_groups_name_active', 'groups', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('agent_group_memberships',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_group_memberships_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_agent_group_memberships_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'group_id', name=op.f('pk_agent_group_memberships'))
    )
    op.create_index('ix_agent_group_memberships_group_id', 'agent_group_memberships', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_group_memberships_group_id', table_name='agent_group_memberships')
    op.drop_table('agent_group_memberships')
    op.drop_index('uq_groups_name_active', table_name='groups', postgresql_where='deleted_at IS NULL')
    op.drop_table('groups')
    # ### end Alembic commands ###
