"""add branch_config table

Revision ID: f05e6e98e85c
Revises: 097b6fc1a2e3
Create Date: 2026-04-20 15:09:55.086114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05e6e98e85c'
down_revision: Union[str, Sequence[str], None] = '097b6fc1a2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('hq_base_url', sa.String(length=512), nullable=True),
    sa.Column('hq_enrollment_token', sa.String(length=512), nullable=True),
    sa.Column('hq_access_token', sa.String(length=512), nullable=True),
    sa.Column('hq_last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hq_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_branch_config_ck_branch_config_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_config')),
    sa.UniqueConstraint('branch_id', name=op.f('uq_branch_config_branch_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branch_config')
    # ### end Alembic commands ###
