/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./shared/ui/badge/Badge.vue')['default']
    Button: typeof import('./shared/ui/button/Button.vue')['default']
    Card: typeof import('./shared/ui/card/Card.vue')['default']
    CardAction: typeof import('./shared/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./shared/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./shared/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./shared/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./shared/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./shared/ui/card/CardTitle.vue')['default']
    DefaultLayout: typeof import('./app/layouts/DefaultLayout.vue')['default']
    Dialog: typeof import('./shared/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./shared/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./shared/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./shared/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./shared/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./shared/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./shared/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./shared/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./shared/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./shared/ui/dialog/DialogTrigger.vue')['default']
    EmptyLayout: typeof import('./app/layouts/EmptyLayout.vue')['default']
    Input: typeof import('./shared/ui/input/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./shared/ui/separator/Separator.vue')['default']
    Sheet: typeof import('./shared/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./shared/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./shared/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./shared/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./shared/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./shared/ui/sheet/SheetHeader.vue')['default']
    SheetOverlay: typeof import('./shared/ui/sheet/SheetOverlay.vue')['default']
    SheetTitle: typeof import('./shared/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./shared/ui/sheet/SheetTrigger.vue')['default']
    Skeleton: typeof import('./shared/ui/skeleton/Skeleton.vue')['default']
    Table: typeof import('./shared/ui/table/Table.vue')['default']
    TableBody: typeof import('./shared/ui/table/TableBody.vue')['default']
    TableCaption: typeof import('./shared/ui/table/TableCaption.vue')['default']
    TableCell: typeof import('./shared/ui/table/TableCell.vue')['default']
    TableEmpty: typeof import('./shared/ui/table/TableEmpty.vue')['default']
    TableFooter: typeof import('./shared/ui/table/TableFooter.vue')['default']
    TableHead: typeof import('./shared/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./shared/ui/table/TableHeader.vue')['default']
    TableRow: typeof import('./shared/ui/table/TableRow.vue')['default']
    Tooltip: typeof import('./shared/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./shared/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./shared/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./shared/ui/tooltip/TooltipTrigger.vue')['default']
    UiConfirmDialog: typeof import('./shared/ui/UiConfirmDialog.vue')['default']
    UiLoadingOverlay: typeof import('./shared/ui/UiLoadingOverlay.vue')['default']
    UiPagination: typeof import('./shared/ui/UiPagination.vue')['default']
    UiToastContainer: typeof import('./shared/ui/UiToastContainer.vue')['default']
  }
}
