/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/sections/navigation/AppFooter.vue')['default']
    AppNavbar: typeof import('./components/sections/navigation/AppNavbar.vue')['default']
    AppSidebar: typeof import('./components/sections/navigation/AppSidebar.vue')['default']
    NavbarBreadcrumbs: typeof import('./components/blocks/navigation/Navbar/NavbarBreadcrumbs.vue')['default']
    NavbarNotification: typeof import('./components/blocks/navigation/Navbar/NavbarNotification.vue')['default']
    NavbarUserInfo: typeof import('./components/blocks/navigation/Navbar/NavbarUserInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarBottomPanel: typeof import('./components/blocks/navigation/Sidebar/SidebarBottomPanel.vue')['default']
    SidebarCentralPanel: typeof import('./components/blocks/navigation/Sidebar/SidebarCentralPanel.vue')['default']
    SidebarTopPanel: typeof import('./components/blocks/navigation/Sidebar/SidebarTopPanel.vue')['default']
    UiConfirmModal: typeof import('./components/ui/UiConfirmModal.vue')['default']
    UiRouteButton: typeof import('./components/ui/UiRouteButton.vue')['default']
    UiTooltip: typeof import('./components/ui/UiTooltip.vue')['default']
  }
}
