/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBootLoader: typeof import('./shared/ui/AppBootLoader.vue')['default']
    AppFooter: typeof import('./app/navigation/sections/AppFooter.vue')['default']
    AppNavbar: typeof import('./app/navigation/sections/AppNavbar.vue')['default']
    AppSidebar: typeof import('./app/navigation/sections/AppSidebar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Dialog: typeof import('primevue/dialog')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    NavbarBreadcrumbs: typeof import('./app/navigation/blocks/Navbar/NavbarBreadcrumbs.vue')['default']
    NavbarUserInfo: typeof import('./app/navigation/blocks/Navbar/NavbarUserInfo.vue')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarCentralPanel: typeof import('./app/navigation/blocks/Sidebar/SidebarCentralPanel.vue')['default']
    SidebarNavLink: typeof import('./app/navigation/blocks/Sidebar/SidebarNavLink.vue')['default']
    SidebarTopPanel: typeof import('./app/navigation/blocks/Sidebar/SidebarTopPanel.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UiConfirmModal: typeof import('./shared/ui/UiConfirmModal.vue')['default']
    UiErrorPage: typeof import('./shared/ui/UiErrorPage.vue')['default']
    UiPageSkeleton: typeof import('./shared/ui/UiPageSkeleton.vue')['default']
    UiTooltip: typeof import('./shared/ui/UiTooltip.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
