export const SERVICE_CATEGORIES = [
  {
    id: 'messengers',
    label: 'Мессенджеры',
    services: [
      {
        id: 'telegram',
        name: 'Telegram',
        rules: [
          { type: 'domain', value: 'telegram.org' },
          { type: 'domain', value: 'telegram.me' },
          { type: 'domain', value: 't.me' },
          { type: 'domain', value: 'web.telegram.org' },
          { type: 'domain', value: 'desktop.telegram.org' },
          { type: 'domain', value: 'core.telegram.org' },
          { type: 'domain', value: 'cdn.telegram.org' },
          { type: 'domain', value: 'tdesktop.com' },
          { type: 'domain', value: 'updates.tdesktop.com' },
          { type: 'ip',     value: '149.154.160.0/20' },
          { type: 'ip',     value: '91.108.4.0/22' },
          { type: 'ip',     value: '91.108.56.0/22' },
          { type: 'ip',     value: '91.108.8.0/22' },
          { type: 'ip',     value: '95.161.64.0/20' },
        ],
      },
      {
        id: 'whatsapp',
        name: 'WhatsApp',
        rules: [
          { type: 'domain', value: 'whatsapp.com' },
          { type: 'domain', value: 'whatsapp.net' },
          { type: 'domain', value: 'wa.me' },
          { type: 'domain', value: 'web.whatsapp.com' },
        ],
      },
      {
        id: 'viber',
        name: 'Viber',
        rules: [
          { type: 'domain', value: 'viber.com' },
          { type: 'domain', value: 'cdn.viber.com' },
          { type: 'domain', value: 'api.viber.com' },
          { type: 'domain', value: 'account.viber.com' },
        ],
      },
      {
        id: 'discord',
        name: 'Discord',
        rules: [
          { type: 'domain', value: 'discord.com' },
          { type: 'domain', value: 'discord.gg' },
          { type: 'domain', value: 'discordapp.com' },
          { type: 'domain', value: 'discordapp.net' },
          { type: 'domain', value: 'discord.media' },
          { type: 'domain', value: 'discordstatus.com' },
          { type: 'domain', value: 'discord.gift' },
        ],
      },
      {
        id: 'skype',
        name: 'Skype',
        rules: [
          { type: 'domain', value: 'skype.com' },
          { type: 'domain', value: 'skypeassets.com' },
          { type: 'domain', value: 'skypeecs-prod-use-0.cloudapp.net' },
          { type: 'domain', value: 'trouter.skype.com' },
        ],
      },
      {
        id: 'signal',
        name: 'Signal',
        rules: [
          { type: 'domain', value: 'signal.org' },
          { type: 'domain', value: 'signal.me' },
          { type: 'domain', value: 'cdn.signal.org' },
          { type: 'domain', value: 'cdn2.signal.org' },
          { type: 'domain', value: 'storage.signal.org' },
          { type: 'domain', value: 'updates.signal.org' },
          { type: 'domain', value: 'sfu.voip.signal.org' },
        ],
      },
      {
        id: 'zoom',
        name: 'Zoom',
        rules: [
          { type: 'domain', value: 'zoom.us' },
          { type: 'domain', value: 'zoom.com' },
          { type: 'domain', value: 'zoomgov.com' },
          { type: 'domain', value: 'zmcdn.net' },
          { type: 'domain', value: 'zoomcdn.net' },
          { type: 'domain', value: 'zoomus.com' },
          { type: 'ip',     value: '3.7.35.0/25' },
          { type: 'ip',     value: '3.21.137.128/25' },
          { type: 'ip',     value: '3.22.11.0/24' },
          { type: 'ip',     value: '3.23.93.0/24' },
        ],
      },
      {
        id: 'slack',
        name: 'Slack',
        rules: [
          { type: 'domain', value: 'slack.com' },
          { type: 'domain', value: 'slack-edge.com' },
          { type: 'domain', value: 'slack-files.com' },
          { type: 'domain', value: 'slack-imgs.com' },
          { type: 'domain', value: 'slack-redir.net' },
          { type: 'domain', value: 'slack-msgs.com' },
          { type: 'domain', value: 'slackb.com' },
        ],
      },
      {
        id: 'teams',
        name: 'Microsoft Teams',
        rules: [
          { type: 'domain', value: 'teams.microsoft.com' },
          { type: 'domain', value: 'teams.live.com' },
          { type: 'domain', value: 'statics.teams.cdn.office.net' },
          { type: 'domain', value: 'api.teams.skype.com' },
          { type: 'domain', value: 'presence.teams.microsoft.com' },
          { type: 'domain', value: 'spacesdiscovery.teams.microsoft.com' },
          { type: 'domain', value: 'msedge.net' },
        ],
      },
      {
        id: 'icq',
        name: 'ICQ',
        rules: [
          { type: 'domain', value: 'icq.com' },
          { type: 'domain', value: 'icq.net' },
          { type: 'domain', value: 'mycdn.me' },
          { type: 'domain', value: 'files.icq.net' },
          { type: 'domain', value: 'u.icq.net' },
        ],
      },
      {
        id: 'threema',
        name: 'Threema',
        rules: [
          { type: 'domain', value: 'threema.ch' },
          { type: 'domain', value: 'cdn.threema.ch' },
          { type: 'ip',     value: '82.220.96.0/24' },
        ],
      },
    ],
  },
  {
    id: 'social',
    label: 'Социальные сети',
    services: [
      {
        id: 'vk',
        name: 'ВКонтакте',
        rules: [
          { type: 'domain', value: 'vk.com' },
          { type: 'domain', value: 'vkontakte.ru' },
          { type: 'domain', value: 'userapi.com' },
          { type: 'domain', value: 'vk-cdn.net' },
          { type: 'domain', value: 'vk.me' },
          { type: 'domain', value: 'vkuser.net' },
          { type: 'domain', value: 'vkuservideo.net' },
          { type: 'domain', value: 'api.vk.com' },
          { type: 'domain', value: 'sun1.userapi.com' },
        ],
      },
      {
        id: 'ok',
        name: 'Одноклассники',
        rules: [
          { type: 'domain', value: 'ok.ru' },
          { type: 'domain', value: 'odnoklassniki.ru' },
          { type: 'domain', value: 'mycdn.me' },
          { type: 'domain', value: 'udn.me' },
          { type: 'domain', value: 'oktelegraph.com' },
        ],
      },
      {
        id: 'facebook',
        name: 'Facebook',
        rules: [
          { type: 'domain', value: 'facebook.com' },
          { type: 'domain', value: 'fb.com' },
          { type: 'domain', value: 'fb.me' },
          { type: 'domain', value: 'fbcdn.net' },
          { type: 'domain', value: 'connect.facebook.net' },
          { type: 'domain', value: 'graph.facebook.com' },
          { type: 'domain', value: 'static.xx.fbcdn.net' },
        ],
      },
      {
        id: 'instagram',
        name: 'Instagram',
        rules: [
          { type: 'domain', value: 'instagram.com' },
          { type: 'domain', value: 'cdninstagram.com' },
          { type: 'domain', value: 'scontent.cdninstagram.com' },
          { type: 'domain', value: 'graph.instagram.com' },
        ],
      },
      {
        id: 'twitter',
        name: 'Twitter / X',
        rules: [
          { type: 'domain', value: 'twitter.com' },
          { type: 'domain', value: 'x.com' },
          { type: 'domain', value: 'twimg.com' },
          { type: 'domain', value: 't.co' },
          { type: 'domain', value: 'abs.twimg.com' },
          { type: 'domain', value: 'api.twitter.com' },
        ],
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        rules: [
          { type: 'domain', value: 'tiktok.com' },
          { type: 'domain', value: 'tiktokcdn.com' },
          { type: 'domain', value: 'tiktokv.com' },
          { type: 'domain', value: 'bytedance.com' },
          { type: 'domain', value: 'ibytedtos.com' },
          { type: 'domain', value: 'ipstatp.com' },
          { type: 'domain', value: 'musical.ly' },
          { type: 'domain', value: 'muscdn.com' },
          { type: 'domain', value: 'tiktokcdn-us.com' },
        ],
      },
      {
        id: 'snapchat',
        name: 'Snapchat',
        rules: [
          { type: 'domain', value: 'snapchat.com' },
          { type: 'domain', value: 'snap.com' },
          { type: 'domain', value: 'snapcdn.com' },
          { type: 'domain', value: 'sc-cdn.net' },
          { type: 'domain', value: 'snapkit.com' },
        ],
      },
      {
        id: 'pinterest',
        name: 'Pinterest',
        rules: [
          { type: 'domain', value: 'pinterest.com' },
          { type: 'domain', value: 'pinimg.com' },
          { type: 'domain', value: 'pinterest.ru' },
          { type: 'domain', value: 'api.pinterest.com' },
        ],
      },
      {
        id: 'linkedin',
        name: 'LinkedIn',
        rules: [
          { type: 'domain', value: 'linkedin.com' },
          { type: 'domain', value: 'licdn.com' },
          { type: 'domain', value: 'lnkd.in' },
          { type: 'domain', value: 'platform.linkedin.com' },
          { type: 'domain', value: 'media.licdn.com' },
        ],
      },
      {
        id: 'reddit',
        name: 'Reddit',
        rules: [
          { type: 'domain', value: 'reddit.com' },
          { type: 'domain', value: 'redd.it' },
          { type: 'domain', value: 'redditmedia.com' },
          { type: 'domain', value: 'redditstatic.com' },
          { type: 'domain', value: 'reddituploads.com' },
          { type: 'domain', value: 'old.reddit.com' },
          { type: 'domain', value: 'i.redd.it' },
          { type: 'domain', value: 'v.redd.it' },
        ],
      },
      {
        id: 'twitch',
        name: 'Twitch',
        rules: [
          { type: 'domain', value: 'twitch.tv' },
          { type: 'domain', value: 'twitchapps.com' },
          { type: 'domain', value: 'jtvnw.net' },
          { type: 'domain', value: 'twitchsvc.net' },
          { type: 'domain', value: 'static.twitchsvc.net' },
          { type: 'domain', value: 'clips.twitch.tv' },
          { type: 'domain', value: 'usher.twitchapps.com' },
        ],
      },
      {
        id: 'kick',
        name: 'Kick',
        rules: [
          { type: 'domain', value: 'kick.com' },
          { type: 'domain', value: 'clips.kick.com' },
          { type: 'domain', value: 'stream.kick.com' },
        ],
      },
      {
        id: 'tumblr',
        name: 'Tumblr',
        rules: [
          { type: 'domain', value: 'tumblr.com' },
          { type: 'domain', value: 'assets.tumblr.com' },
          { type: 'domain', value: 'media.tumblr.com' },
        ],
      },
    ],
  },
  {
    id: 'yandex',
    label: 'Яндекс',
    services: [
      {
        id: 'yandex_search',
        name: 'Поиск',
        rules: [
          { type: 'domain', value: 'yandex.ru' },
          { type: 'domain', value: 'yandex.com' },
          { type: 'domain', value: 'ya.ru' },
          { type: 'domain', value: 'yastatic.net' },
          { type: 'domain', value: 'yandex.net' },
          { type: 'domain', value: 'avatars.mds.yandex.net' },
          { type: 'domain', value: 'mc.yandex.ru' },
        ],
      },
      {
        id: 'yandex_games',
        name: 'Яндекс Игры',
        rules: [
          { type: 'domain', value: 'games.yandex.ru' },
          { type: 'domain', value: 'games.yandex.net' },
          { type: 'domain', value: 'yandex.net' },
          { type: 'domain', value: 'yastatic.net' },
          { type: 'domain', value: 'avatars.mds.yandex.net' },
          { type: 'domain', value: 'storage.yandex.net' },
        ],
      },
      {
        id: 'yandex_music',
        name: 'Яндекс Музыка',
        rules: [
          { type: 'domain', value: 'music.yandex.ru' },
          { type: 'domain', value: 'music.yandex.com' },
          { type: 'domain', value: 'storage.mds.yandex.net' },
          { type: 'domain', value: 'yastatic.net' },
        ],
      },
      {
        id: 'yandex_disk',
        name: 'Яндекс Диск',
        rules: [
          { type: 'domain', value: 'disk.yandex.ru' },
          { type: 'domain', value: 'disk.yandex.com' },
          { type: 'domain', value: 'downloader.disk.yandex.net' },
          { type: 'domain', value: 'webdav.yandex.ru' },
          { type: 'domain', value: 'storage.mds.yandex.net' },
          { type: 'domain', value: 'yastatic.net' },
        ],
      },
      {
        id: 'yandex_mail',
        name: 'Яндекс Почта',
        rules: [
          { type: 'domain', value: 'mail.yandex.ru' },
          { type: 'domain', value: 'mail.yandex.com' },
          { type: 'domain', value: 'yandex.ru' },
          { type: 'domain', value: 'yastatic.net' },
          { type: 'domain', value: 'avatars.mds.yandex.net' },
        ],
      },
      {
        id: 'yandex_maps',
        name: 'Яндекс Карты',
        rules: [
          { type: 'domain', value: 'maps.yandex.ru' },
          { type: 'domain', value: 'maps.yandex.com' },
          { type: 'domain', value: 'api-maps.yandex.ru' },
          { type: 'domain', value: 'core-renderer-tiles.maps.yandex.net' },
          { type: 'domain', value: 'yastatic.net' },
        ],
      },
      {
        id: 'yandex_market',
        name: 'Яндекс Маркет',
        rules: [
          { type: 'domain', value: 'market.yandex.ru' },
          { type: 'domain', value: 'market.yandex.com' },
          { type: 'domain', value: 'beru.ru' },
          { type: 'domain', value: 'yastatic.net' },
          { type: 'domain', value: 'avatars.mds.yandex.net' },
        ],
      },
      {
        id: 'yandex_taxi',
        name: 'Яндекс Go / Такси',
        rules: [
          { type: 'domain', value: 'taxi.yandex.ru' },
          { type: 'domain', value: 'go.yandex.ru' },
          { type: 'domain', value: 'taxi.yandex.com' },
          { type: 'domain', value: 'yango.com' },
          { type: 'domain', value: 'yastatic.net' },
        ],
      },
      {
        id: 'yandex_alice',
        name: 'Алиса / Яндекс Станция',
        rules: [
          { type: 'domain', value: 'dialogs.yandex.ru' },
          { type: 'domain', value: 'alicekit.yandex.ru' },
          { type: 'domain', value: 'quasar.yandex.net' },
          { type: 'domain', value: 'quasar.yandex.ru' },
          { type: 'domain', value: 'yandex.net' },
          { type: 'domain', value: 'yastatic.net' },
        ],
      },
      {
        id: 'yandex_browser',
        name: 'Яндекс Браузер',
        rules: [
          { type: 'domain', value: 'browser.yandex.ru' },
          { type: 'domain', value: 'browser.yandex.com' },
          { type: 'domain', value: 'api.browser.yandex.com' },
          { type: 'domain', value: 'yastatic.net' },
        ],
      },
      {
        id: 'kinopoisk',
        name: 'Кинопоиск',
        rules: [
          { type: 'domain', value: 'kinopoisk.ru' },
          { type: 'domain', value: 'hd.kinopoisk.ru' },
          { type: 'domain', value: 'yastatic.net' },
          { type: 'domain', value: 'avatars.mds.yandex.net' },
          { type: 'domain', value: 'strm.yandex.net' },
        ],
      },
    ],
  },
  {
    id: 'video',
    label: 'Видео и кино',
    services: [
      {
        id: 'youtube',
        name: 'YouTube',
        rules: [
          { type: 'domain', value: 'youtube.com' },
          { type: 'domain', value: 'youtu.be' },
          { type: 'domain', value: 'googlevideo.com' },
          { type: 'domain', value: 'ytimg.com' },
          { type: 'domain', value: 'yt3.ggpht.com' },
          { type: 'domain', value: 'youtube-nocookie.com' },
          { type: 'domain', value: 'music.youtube.com' },
          { type: 'domain', value: 'youtube.googleapis.com' },
        ],
      },
      {
        id: 'netflix',
        name: 'Netflix',
        rules: [
          { type: 'domain', value: 'netflix.com' },
          { type: 'domain', value: 'nflximg.net' },
          { type: 'domain', value: 'nflxext.com' },
          { type: 'domain', value: 'nflxso.net' },
          { type: 'domain', value: 'nflxvideo.net' },
          { type: 'domain', value: 'fast.com' },
        ],
      },
      {
        id: 'ivi',
        name: 'IVI',
        rules: [
          { type: 'domain', value: 'ivi.ru' },
          { type: 'domain', value: 'cdn.ivi.ru' },
          { type: 'domain', value: 'api.digitalaccess.ru' },
          { type: 'domain', value: 'thumbnails.ivi.ru' },
        ],
      },
      {
        id: 'okko',
        name: 'Okko',
        rules: [
          { type: 'domain', value: 'okko.tv' },
          { type: 'domain', value: 'cdn.okko.tv' },
          { type: 'domain', value: 'api.okko.tv' },
        ],
      },
      {
        id: 'start',
        name: 'START',
        rules: [
          { type: 'domain', value: 'start.ru' },
          { type: 'domain', value: 'cdn.start.ru' },
        ],
      },
      {
        id: 'moretv',
        name: 'MORE.tv',
        rules: [
          { type: 'domain', value: 'more.tv' },
          { type: 'domain', value: 'cdn.more.tv' },
        ],
      },
      {
        id: 'wink',
        name: 'Wink',
        rules: [
          { type: 'domain', value: 'wink.ru' },
          { type: 'domain', value: 'cdn.wink.ru' },
          { type: 'domain', value: 'api.wink.ru' },
        ],
      },
      {
        id: 'premier',
        name: 'Premier',
        rules: [
          { type: 'domain', value: 'premier.one' },
          { type: 'domain', value: 'cdn.premier.one' },
        ],
      },
      {
        id: 'rutube',
        name: 'Rutube',
        rules: [
          { type: 'domain', value: 'rutube.ru' },
          { type: 'domain', value: 'cdn.rutube.ru' },
          { type: 'domain', value: 'strm.yandex.net' },
          { type: 'domain', value: 'pics.rutube.ru' },
        ],
      },
      {
        id: 'smotrim',
        name: 'Смотрим (ВГТРК)',
        rules: [
          { type: 'domain', value: 'smotrim.ru' },
          { type: 'domain', value: 'cdn.smotrim.ru' },
          { type: 'domain', value: 'api.smotrim.ru' },
        ],
      },
      {
        id: 'vimeo',
        name: 'Vimeo',
        rules: [
          { type: 'domain', value: 'vimeo.com' },
          { type: 'domain', value: 'vimeocdn.com' },
          { type: 'domain', value: 'player.vimeo.com' },
        ],
      },
      {
        id: 'dailymotion',
        name: 'Dailymotion',
        rules: [
          { type: 'domain', value: 'dailymotion.com' },
          { type: 'domain', value: 'dmcdn.net' },
          { type: 'domain', value: 'dm.gg' },
        ],
      },
      {
        id: 'crunchyroll',
        name: 'Crunchyroll',
        rules: [
          { type: 'domain', value: 'crunchyroll.com' },
          { type: 'domain', value: 'static.crunchyroll.com' },
          { type: 'domain', value: 'img1.ak.crunchyroll.com' },
          { type: 'domain', value: 'subs.crunchyroll.com' },
        ],
      },
    ],
  },
  {
    id: 'music',
    label: 'Музыка',
    services: [
      {
        id: 'spotify',
        name: 'Spotify',
        rules: [
          { type: 'domain', value: 'spotify.com' },
          { type: 'domain', value: 'scdn.co' },
          { type: 'domain', value: 'spotifycdn.com' },
          { type: 'domain', value: 'audio-ak.spotify.com' },
          { type: 'domain', value: 'audio-akp.spotify.com' },
          { type: 'domain', value: 'open.spotify.com' },
          { type: 'domain', value: 'api.spotify.com' },
        ],
      },
      {
        id: 'soundcloud',
        name: 'SoundCloud',
        rules: [
          { type: 'domain', value: 'soundcloud.com' },
          { type: 'domain', value: 'sndcdn.com' },
          { type: 'domain', value: 'api-v2.soundcloud.com' },
        ],
      },
      {
        id: 'deezer',
        name: 'Deezer',
        rules: [
          { type: 'domain', value: 'deezer.com' },
          { type: 'domain', value: 'dzcdn.net' },
          { type: 'domain', value: 'api.deezer.com' },
        ],
      },
      {
        id: 'applemusic',
        name: 'Apple Music',
        rules: [
          { type: 'domain', value: 'music.apple.com' },
          { type: 'domain', value: 'itunes.apple.com' },
          { type: 'domain', value: 'mzstatic.com' },
          { type: 'domain', value: 'apple.com' },
          { type: 'domain', value: 'aaplimg.com' },
        ],
      },
      {
        id: 'yandexmusic',
        name: 'Яндекс Музыка',
        rules: [
          { type: 'domain', value: 'music.yandex.ru' },
          { type: 'domain', value: 'music.yandex.com' },
          { type: 'domain', value: 'storage.mds.yandex.net' },
          { type: 'domain', value: 'yastatic.net' },
        ],
      },
      {
        id: 'vkmusic',
        name: 'VK Музыка',
        rules: [
          { type: 'domain', value: 'vk.com' },
          { type: 'domain', value: 'userapi.com' },
          { type: 'domain', value: 'vk-cdn.net' },
        ],
      },
      {
        id: 'tidal',
        name: 'Tidal',
        rules: [
          { type: 'domain', value: 'tidal.com' },
          { type: 'domain', value: 'listen.tidal.com' },
          { type: 'domain', value: 'sp.audio.tidal.com' },
        ],
      },
      {
        id: 'zvuk',
        name: 'Звук (Сбер)',
        rules: [
          { type: 'domain', value: 'zvuk.com' },
          { type: 'domain', value: 'cdn.zvuk.com' },
          { type: 'domain', value: 'api.zvuk.com' },
        ],
      },
    ],
  },
  {
    id: 'gaming',
    label: 'Игры',
    services: [
      {
        id: 'steam',
        name: 'Steam',
        rules: [
          { type: 'domain', value: 'steampowered.com' },
          { type: 'domain', value: 'steamcommunity.com' },
          { type: 'domain', value: 'steamstatic.com' },
          { type: 'domain', value: 'steamusercontent.com' },
          { type: 'domain', value: 'steamgames.com' },
          { type: 'domain', value: 'steam.com' },
          { type: 'domain', value: 'valvesoftware.com' },
          { type: 'ip',     value: '104.64.0.0/10' },
          { type: 'ip',     value: '185.25.180.0/22' },
          { type: 'ip',     value: '208.64.200.0/22' },
        ],
      },
      {
        id: 'epicgames',
        name: 'Epic Games',
        rules: [
          { type: 'domain', value: 'epicgames.com' },
          { type: 'domain', value: 'store.epicgames.com' },
          { type: 'domain', value: 'unrealengine.com' },
          { type: 'domain', value: 'epicgcdn.co' },
          { type: 'domain', value: 'fortnite.com' },
          { type: 'domain', value: 'fn.epicgames.com' },
        ],
      },
      {
        id: 'roblox',
        name: 'Roblox',
        rules: [
          { type: 'domain', value: 'roblox.com' },
          { type: 'domain', value: 'rbxcdn.com' },
          { type: 'domain', value: 'robloxlabs.com' },
          { type: 'domain', value: 'rbxtrk.com' },
          { type: 'domain', value: 'setup.rbxcdn.com' },
          { type: 'domain', value: 'clientsettings.roblox.com' },
          { type: 'domain', value: 'www.roblox.com' },
        ],
      },
      {
        id: 'minecraft',
        name: 'Minecraft',
        rules: [
          { type: 'domain', value: 'minecraft.net' },
          { type: 'domain', value: 'mojang.com' },
          { type: 'domain', value: 'minecraftservices.com' },
          { type: 'domain', value: 'api.minecraftservices.com' },
          { type: 'domain', value: 'sessionserver.mojang.com' },
          { type: 'domain', value: 'textures.minecraft.net' },
        ],
      },
      {
        id: 'blizzard',
        name: 'Blizzard / Battle.net',
        rules: [
          { type: 'domain', value: 'battle.net' },
          { type: 'domain', value: 'blizzard.com' },
          { type: 'domain', value: 'blzddist1-a.akamaihd.net' },
          { type: 'domain', value: 'worldofwarcraft.com' },
          { type: 'domain', value: 'overwatch.com' },
          { type: 'domain', value: 'hearthstone.com' },
          { type: 'domain', value: 'starcraft2.com' },
        ],
      },
      {
        id: 'riot',
        name: 'Riot Games',
        rules: [
          { type: 'domain', value: 'riotgames.com' },
          { type: 'domain', value: 'leagueoflegends.com' },
          { type: 'domain', value: 'valorant.com' },
          { type: 'domain', value: 'riotcdn.net' },
          { type: 'domain', value: 'teamfighttactics.leagueoflegends.com' },
          { type: 'domain', value: 'ddragon.leagueoflegends.com' },
        ],
      },
      {
        id: 'ea',
        name: 'EA / Origin',
        rules: [
          { type: 'domain', value: 'ea.com' },
          { type: 'domain', value: 'origin.com' },
          { type: 'domain', value: 'eaassets-a.akamaihd.net' },
          { type: 'domain', value: 'dm.origin.com' },
          { type: 'domain', value: 'akamai-ea.com' },
        ],
      },
      {
        id: 'ubisoft',
        name: 'Ubisoft / Ubisoft Connect',
        rules: [
          { type: 'domain', value: 'ubisoft.com' },
          { type: 'domain', value: 'ubisoftconnect.com' },
          { type: 'domain', value: 'ubi.com' },
          { type: 'domain', value: 'ubistatic-a.akamaihd.net' },
          { type: 'domain', value: 'cdn.ubi.com' },
          { type: 'domain', value: 'static.ubi.com' },
        ],
      },
      {
        id: 'wargaming',
        name: 'Wargaming (WoT / WoWs)',
        rules: [
          { type: 'domain', value: 'wargaming.net' },
          { type: 'domain', value: 'worldoftanks.ru' },
          { type: 'domain', value: 'worldoftanks.eu' },
          { type: 'domain', value: 'worldofwarships.ru' },
          { type: 'domain', value: 'worldofwarships.eu' },
          { type: 'domain', value: 'wgcdn.net' },
          { type: 'domain', value: 'wo-ra.ru' },
          { type: 'ip',     value: '193.29.56.0/21' },
        ],
      },
      {
        id: 'gaijin',
        name: 'Gaijin / War Thunder',
        rules: [
          { type: 'domain', value: 'gaijin.net' },
          { type: 'domain', value: 'warthunder.com' },
          { type: 'domain', value: 'warthunder.ru' },
          { type: 'domain', value: 'cdn.gaijin.net' },
          { type: 'domain', value: 'login.gaijin.net' },
        ],
      },
      {
        id: 'eft',
        name: 'Escape from Tarkov',
        rules: [
          { type: 'domain', value: 'escapefromtarkov.com' },
          { type: 'domain', value: 'battlestategames.com' },
          { type: 'domain', value: 'prod.escapefromtarkov.com' },
          { type: 'domain', value: 'launcher.escapefromtarkov.com' },
        ],
      },
      {
        id: 'xbox',
        name: 'Xbox / Microsoft Gaming',
        rules: [
          { type: 'domain', value: 'xbox.com' },
          { type: 'domain', value: 'xboxlive.com' },
          { type: 'domain', value: 'xboxservices.com' },
          { type: 'domain', value: 'live.com' },
          { type: 'domain', value: 'gssv-prod-0.xboxlive.com' },
          { type: 'domain', value: 'xgamingservices.com' },
        ],
      },
      {
        id: 'psn',
        name: 'PlayStation Network',
        rules: [
          { type: 'domain', value: 'playstation.com' },
          { type: 'domain', value: 'playstation.net' },
          { type: 'domain', value: 'ps4.update.playstation.net' },
          { type: 'domain', value: 'sony.com' },
          { type: 'domain', value: 'gs2.ww.prod.dl.playstation.net' },
        ],
      },
      {
        id: 'nintendo',
        name: 'Nintendo / Switch Online',
        rules: [
          { type: 'domain', value: 'nintendo.com' },
          { type: 'domain', value: 'nintendo.net' },
          { type: 'domain', value: 'nintendo.ru' },
          { type: 'domain', value: 'eshop.nintendo.net' },
          { type: 'domain', value: 'cdn.nintendo.svc.akamaized.net' },
          { type: 'domain', value: 'geisha-wup.cdn.nintendo.net' },
          { type: 'domain', value: 'tagaya.wup.shop.nintendo.net' },
        ],
      },
      {
        id: 'vkplay',
        name: 'VK Play / MY.GAMES',
        rules: [
          { type: 'domain', value: 'vkplay.ru' },
          { type: 'domain', value: 'my.games' },
          { type: 'domain', value: 'mygames.com' },
          { type: 'domain', value: 'cdn.vkplay.ru' },
          { type: 'domain', value: 'mygames.download' },
        ],
      },
      {
        id: 'gog',
        name: 'GOG',
        rules: [
          { type: 'domain', value: 'gog.com' },
          { type: 'domain', value: 'gogcdn.net' },
          { type: 'domain', value: 'items.gog.com' },
          { type: 'domain', value: 'cdn.gog.com' },
        ],
      },
      {
        id: 'yandex_games_gaming',
        name: 'Яндекс Игры',
        rules: [
          { type: 'domain', value: 'games.yandex.ru' },
          { type: 'domain', value: 'games.yandex.net' },
          { type: 'domain', value: 'yandex.net' },
          { type: 'domain', value: 'yastatic.net' },
          { type: 'domain', value: 'avatars.mds.yandex.net' },
        ],
      },
      {
        id: 'supercell',
        name: 'Supercell (Clash of Clans)',
        rules: [
          { type: 'domain', value: 'supercell.com' },
          { type: 'domain', value: 'supercell.net' },
          { type: 'domain', value: 'clashofclans.com' },
          { type: 'domain', value: 'clashroyale.com' },
          { type: 'domain', value: 'boombeach.com' },
          { type: 'domain', value: 'brawhallastars.com' },
          { type: 'ip',     value: '93.190.142.0/23' },
        ],
      },
      {
        id: 'king',
        name: 'King (Candy Crush)',
        rules: [
          { type: 'domain', value: 'king.com' },
          { type: 'domain', value: 'kingusercontent.com' },
          { type: 'domain', value: 'adjust.com' },
          { type: 'domain', value: 'api.king.com' },
        ],
      },
      {
        id: 'genshin',
        name: 'Genshin Impact (HoYoverse)',
        rules: [
          { type: 'domain', value: 'hoyoverse.com' },
          { type: 'domain', value: 'mihoyo.com' },
          { type: 'domain', value: 'genshin.hoyoverse.com' },
          { type: 'domain', value: 'overseacdn.yuanshen.com' },
          { type: 'domain', value: 'log-upload-os.hoyoverse.com' },
        ],
      },
      {
        id: 'dota2',
        name: 'Dota 2',
        rules: [
          { type: 'domain', value: 'dota2.com' },
          { type: 'domain', value: 'steampowered.com' },
          { type: 'domain', value: 'steamcommunity.com' },
          { type: 'ip',     value: '185.25.180.0/22' },
          { type: 'ip',     value: '208.64.200.0/22' },
        ],
      },
      {
        id: 'cs2',
        name: 'CS2 / CS:GO',
        rules: [
          { type: 'domain', value: 'steampowered.com' },
          { type: 'domain', value: 'steamcommunity.com' },
          { type: 'domain', value: 'counter-strike.net' },
          { type: 'ip',     value: '185.25.180.0/22' },
          { type: 'ip',     value: '208.64.200.0/22' },
          { type: 'ip',     value: '146.66.152.0/24' },
        ],
      },
    ],
  },
  {
    id: 'marketplace',
    label: 'Маркетплейсы',
    services: [
      {
        id: 'wildberries',
        name: 'Wildberries',
        rules: [
          { type: 'domain', value: 'wildberries.ru' },
          { type: 'domain', value: 'wbstatic.net' },
          { type: 'domain', value: 'wbbasket.ru' },
          { type: 'domain', value: 'xcdn.wbstatic.net' },
          { type: 'domain', value: 'basket-01.wb.ru' },
          { type: 'domain', value: 'images.wbstatic.net' },
        ],
      },
      {
        id: 'ozon',
        name: 'Ozon',
        rules: [
          { type: 'domain', value: 'ozon.ru' },
          { type: 'domain', value: 'cdn1.ozone.ru' },
          { type: 'domain', value: 'static.ozone.ru' },
          { type: 'domain', value: 'api.ozon.ru' },
          { type: 'domain', value: 'st.ozone.ru' },
        ],
      },
      {
        id: 'avito',
        name: 'Авито',
        rules: [
          { type: 'domain', value: 'avito.ru' },
          { type: 'domain', value: 'cdn.avito.ru' },
          { type: 'domain', value: 'static.avito.ru' },
          { type: 'domain', value: 'im.avito.ru' },
          { type: 'domain', value: 'api.avito.ru' },
        ],
      },
      {
        id: 'aliexpress',
        name: 'AliExpress',
        rules: [
          { type: 'domain', value: 'aliexpress.com' },
          { type: 'domain', value: 'aliexpress.ru' },
          { type: 'domain', value: 'ae01.alicdn.com' },
          { type: 'domain', value: 'alicdn.com' },
          { type: 'domain', value: 'alibaba.com' },
          { type: 'domain', value: 'alipay.com' },
        ],
      },
      {
        id: 'lamoda',
        name: 'Lamoda',
        rules: [
          { type: 'domain', value: 'lamoda.ru' },
          { type: 'domain', value: 'static.lmcdn.ru' },
          { type: 'domain', value: 'lmcdn.ru' },
        ],
      },
      {
        id: 'sbermegamarket',
        name: 'СберМегаМаркет',
        rules: [
          { type: 'domain', value: 'megamarket.ru' },
          { type: 'domain', value: 'sbermegamarket.ru' },
          { type: 'domain', value: 'cdn.sbermegamarket.ru' },
        ],
      },
      {
        id: 'dns',
        name: 'DNS',
        rules: [
          { type: 'domain', value: 'dns-shop.ru' },
          { type: 'domain', value: 'cdn.dns-shop.ru' },
          { type: 'domain', value: 'cdn2.dns-shop.ru' },
        ],
      },
      {
        id: 'mvideo',
        name: 'М.Видео',
        rules: [
          { type: 'domain', value: 'mvideo.ru' },
          { type: 'domain', value: 'eldo.ru' },
          { type: 'domain', value: 'static.mvideo.ru' },
        ],
      },
    ],
  },
  {
    id: 'work',
    label: 'Работа',
    services: [
      {
        id: 'github',
        name: 'GitHub',
        rules: [
          { type: 'domain', value: 'github.com' },
          { type: 'domain', value: 'githubusercontent.com' },
          { type: 'domain', value: 'github.io' },
          { type: 'domain', value: 'githubassets.com' },
          { type: 'domain', value: 'api.github.com' },
          { type: 'domain', value: 'codeload.github.com' },
        ],
      },
      {
        id: 'gitlab',
        name: 'GitLab',
        rules: [
          { type: 'domain', value: 'gitlab.com' },
          { type: 'domain', value: 'gitlab.io' },
          { type: 'domain', value: 'gitlabstatus.com' },
        ],
      },
      {
        id: 'notion',
        name: 'Notion',
        rules: [
          { type: 'domain', value: 'notion.so' },
          { type: 'domain', value: 'notion.com' },
          { type: 'domain', value: 's3-us-west-2.amazonaws.com' },
          { type: 'domain', value: 'prod-files-secure.s3.us-west-2.amazonaws.com' },
        ],
      },
      {
        id: 'figma',
        name: 'Figma',
        rules: [
          { type: 'domain', value: 'figma.com' },
          { type: 'domain', value: 'figma-alpha-api.s3.us-west-2.amazonaws.com' },
          { type: 'domain', value: 'static.figma.com' },
          { type: 'domain', value: 'fonts.figma.com' },
        ],
      },
      {
        id: 'atlassian',
        name: 'Atlassian (Jira / Confluence)',
        rules: [
          { type: 'domain', value: 'atlassian.com' },
          { type: 'domain', value: 'atlassian.net' },
          { type: 'domain', value: 'jira.atlassian.com' },
          { type: 'domain', value: 'confluence.atlassian.com' },
          { type: 'domain', value: 'bitbucket.org' },
          { type: 'domain', value: 'atlaskit.atlassian.com' },
        ],
      },
      {
        id: 'google_workspace',
        name: 'Google Workspace',
        rules: [
          { type: 'domain', value: 'google.com' },
          { type: 'domain', value: 'googleapis.com' },
          { type: 'domain', value: 'gmail.com' },
          { type: 'domain', value: 'drive.google.com' },
          { type: 'domain', value: 'docs.google.com' },
          { type: 'domain', value: 'meet.google.com' },
          { type: 'domain', value: 'chat.google.com' },
          { type: 'domain', value: 'calendar.google.com' },
          { type: 'domain', value: 'googleusercontent.com' },
        ],
      },
      {
        id: 'microsoft365',
        name: 'Microsoft 365',
        rules: [
          { type: 'domain', value: 'office.com' },
          { type: 'domain', value: 'office365.com' },
          { type: 'domain', value: 'microsoftonline.com' },
          { type: 'domain', value: 'sharepoint.com' },
          { type: 'domain', value: 'onedrive.com' },
          { type: 'domain', value: 'outlook.com' },
          { type: 'domain', value: 'cdn.office.net' },
        ],
      },
      {
        id: 'jetbrains',
        name: 'JetBrains',
        rules: [
          { type: 'domain', value: 'jetbrains.com' },
          { type: 'domain', value: 'download.jetbrains.com' },
          { type: 'domain', value: 'plugins.jetbrains.com' },
          { type: 'domain', value: 'account.jetbrains.com' },
        ],
      },
      {
        id: 'trello',
        name: 'Trello',
        rules: [
          { type: 'domain', value: 'trello.com' },
          { type: 'domain', value: 'trellocdn.com' },
          { type: 'domain', value: 'trello-attachments.s3.amazonaws.com' },
        ],
      },
      {
        id: 'miro',
        name: 'Miro',
        rules: [
          { type: 'domain', value: 'miro.com' },
          { type: 'domain', value: 'miro.com' },
          { type: 'domain', value: 'miro-realtime.com' },
          { type: 'domain', value: 'static.miro.com' },
        ],
      },
      {
        id: 'bitrix24',
        name: 'Битрикс24',
        rules: [
          { type: 'domain', value: 'bitrix24.ru' },
          { type: 'domain', value: 'bitrix24.com' },
          { type: 'domain', value: 'cdn.bitrix24.ru' },
          { type: 'domain', value: 'bitrix.ru' },
        ],
      },
    ],
  },
  {
    id: 'other',
    label: 'Прочее',
    services: [
      {
        id: '9gag',
        name: '9GAG',
        rules: [
          { type: 'domain', value: '9gag.com' },
          { type: 'domain', value: 'img-9gag-fun.9cache.com' },
          { type: 'domain', value: '9cache.com' },
        ],
      },
      {
        id: 'imgur',
        name: 'Imgur',
        rules: [
          { type: 'domain', value: 'imgur.com' },
          { type: 'domain', value: 'i.imgur.com' },
        ],
      },
      {
        id: 'onlyfans',
        name: 'OnlyFans',
        rules: [
          { type: 'domain', value: 'onlyfans.com' },
          { type: 'domain', value: 'cdn3.onlyfans.com' },
          { type: 'domain', value: 'public.onlyfans.com' },
        ],
      },
      {
        id: 'patreon',
        name: 'Patreon',
        rules: [
          { type: 'domain', value: 'patreon.com' },
          { type: 'domain', value: 'c10.patreon.com' },
          { type: 'domain', value: 'api.patreon.com' },
        ],
      },
      {
        id: 'habr',
        name: 'Хабр',
        rules: [
          { type: 'domain', value: 'habr.com' },
          { type: 'domain', value: 'habrastorage.org' },
          { type: 'domain', value: 'tmssl.akamaized.net' },
        ],
      },
      {
        id: '2gis',
        name: '2ГИС',
        rules: [
          { type: 'domain', value: '2gis.ru' },
          { type: 'domain', value: '2gis.com' },
          { type: 'domain', value: 'tile3.maps.2gis.com' },
          { type: 'domain', value: 'catalog.api.2gis.com' },
        ],
      },
      {
        id: 'booking',
        name: 'Booking.com',
        rules: [
          { type: 'domain', value: 'booking.com' },
          { type: 'domain', value: 'bstatic.com' },
          { type: 'domain', value: 'cf.bstatic.com' },
        ],
      },
      {
        id: 'gosuslugi',
        name: 'Госуслуги',
        rules: [
          { type: 'domain', value: 'gosuslugi.ru' },
          { type: 'domain', value: 'esia.gosuslugi.ru' },
          { type: 'domain', value: 'cdn.gosuslugi.ru' },
          { type: 'domain', value: 'static.gosuslugi.ru' },
        ],
      },
      {
        id: 'sberbank',
        name: 'Сбербанк / СберБанк Онлайн',
        rules: [
          { type: 'domain', value: 'sberbank.ru' },
          { type: 'domain', value: 'online.sberbank.ru' },
          { type: 'domain', value: 'sber.ru' },
          { type: 'domain', value: 'cdn.sberbank.ru' },
        ],
      },
      {
        id: 'tinkoff',
        name: 'Т-Банк (Тинькофф)',
        rules: [
          { type: 'domain', value: 'tinkoff.ru' },
          { type: 'domain', value: 't.tinkoff.ru' },
          { type: 'domain', value: 'cdn.tinkoff.ru' },
          { type: 'domain', value: 'acdn.tinkoff.ru' },
        ],
      },
    ],
  },
  {
    id: 'ai',
    label: 'Нейросети',
    services: [
      {
        id: 'chatgpt',
        name: 'ChatGPT / OpenAI',
        rules: [
          { type: 'domain', value: 'openai.com' },
          { type: 'domain', value: 'chatgpt.com' },
          { type: 'domain', value: 'api.openai.com' },
          { type: 'domain', value: 'cdn.openai.com' },
          { type: 'domain', value: 'oaistatic.com' },
          { type: 'domain', value: 'oaiusercontent.com' },
        ],
      },
      {
        id: 'claude',
        name: 'Claude / Anthropic',
        rules: [
          { type: 'domain', value: 'anthropic.com' },
          { type: 'domain', value: 'claude.ai' },
          { type: 'domain', value: 'api.anthropic.com' },
          { type: 'domain', value: 'cdn.anthropic.com' },
        ],
      },
      {
        id: 'gemini',
        name: 'Gemini / Google AI',
        rules: [
          { type: 'domain', value: 'gemini.google.com' },
          { type: 'domain', value: 'ai.google.dev' },
          { type: 'domain', value: 'generativelanguage.googleapis.com' },
          { type: 'domain', value: 'deepmind.google' },
          { type: 'domain', value: 'deepmind.com' },
          { type: 'domain', value: 'aistudio.google.com' },
        ],
      },
      {
        id: 'copilot',
        name: 'Microsoft Copilot',
        rules: [
          { type: 'domain', value: 'copilot.microsoft.com' },
          { type: 'domain', value: 'bing.com' },
          { type: 'domain', value: 'sydney.bing.com' },
          { type: 'domain', value: 'edgeservices.bing.com' },
          { type: 'domain', value: 'copilot.cloud.microsoft' },
        ],
      },
      {
        id: 'grok',
        name: 'Grok / xAI',
        rules: [
          { type: 'domain', value: 'grok.com' },
          { type: 'domain', value: 'x.ai' },
          { type: 'domain', value: 'grok.x.ai' },
          { type: 'domain', value: 'api.x.ai' },
        ],
      },
      {
        id: 'deepseek',
        name: 'DeepSeek',
        rules: [
          { type: 'domain', value: 'deepseek.com' },
          { type: 'domain', value: 'chat.deepseek.com' },
          { type: 'domain', value: 'api.deepseek.com' },
          { type: 'domain', value: 'cdn.deepseek.com' },
        ],
      },
      {
        id: 'mistral',
        name: 'Mistral AI',
        rules: [
          { type: 'domain', value: 'mistral.ai' },
          { type: 'domain', value: 'chat.mistral.ai' },
          { type: 'domain', value: 'api.mistral.ai' },
          { type: 'domain', value: 'console.mistral.ai' },
        ],
      },
      {
        id: 'perplexity',
        name: 'Perplexity',
        rules: [
          { type: 'domain', value: 'perplexity.ai' },
          { type: 'domain', value: 'www.perplexity.ai' },
          { type: 'domain', value: 'cdn.perplexity.ai' },
          { type: 'domain', value: 'labs.perplexity.ai' },
        ],
      },
      {
        id: 'poe',
        name: 'Poe',
        rules: [
          { type: 'domain', value: 'poe.com' },
          { type: 'domain', value: 'poecdn.com' },
          { type: 'domain', value: 'quora.com' },
        ],
      },
      {
        id: 'character_ai',
        name: 'Character.AI',
        rules: [
          { type: 'domain', value: 'character.ai' },
          { type: 'domain', value: 'characterai.io' },
          { type: 'domain', value: 'cdn.character.ai' },
        ],
      },
      {
        id: 'midjourney',
        name: 'Midjourney',
        rules: [
          { type: 'domain', value: 'midjourney.com' },
          { type: 'domain', value: 'cdn.midjourney.com' },
          { type: 'domain', value: 'discord.com' },
          { type: 'domain', value: 'discordapp.com' },
        ],
      },
      {
        id: 'stability',
        name: 'Stable Diffusion / Stability AI',
        rules: [
          { type: 'domain', value: 'stability.ai' },
          { type: 'domain', value: 'dreamstudio.ai' },
          { type: 'domain', value: 'clipdrop.co' },
          { type: 'domain', value: 'stablediffusionweb.com' },
          { type: 'domain', value: 'cdn.stability.ai' },
        ],
      },
      {
        id: 'gigachat',
        name: 'GigaChat / Сбер AI',
        rules: [
          { type: 'domain', value: 'gigachat.sber.ru' },
          { type: 'domain', value: 'sber.ai' },
          { type: 'domain', value: 'developers.sber.ru' },
          { type: 'domain', value: 'cdn.sber.ai' },
        ],
      },
      {
        id: 'kandinsky',
        name: 'Kandinsky / FusionBrain',
        rules: [
          { type: 'domain', value: 'fusionbrain.ai' },
          { type: 'domain', value: 'cdn.fusionbrain.ai' },
          { type: 'domain', value: 'kandinsky.sber.ru' },
        ],
      },
      {
        id: 'yandex_gpt',
        name: 'YandexGPT',
        rules: [
          { type: 'domain', value: '300.ya.ru' },
          { type: 'domain', value: 'ya.ru' },
          { type: 'domain', value: 'yandex.ru' },
          { type: 'domain', value: 'foundation-models.api.cloud.yandex.net' },
          { type: 'domain', value: 'yastatic.net' },
        ],
      },
      {
        id: 'huggingface',
        name: 'Hugging Face',
        rules: [
          { type: 'domain', value: 'huggingface.co' },
          { type: 'domain', value: 'hf.space' },
          { type: 'domain', value: 'huggingface.com' },
          { type: 'domain', value: 'cdn-lfs.huggingface.co' },
          { type: 'domain', value: 'cdn-lfs-us-1.huggingface.co' },
        ],
      },
      {
        id: 'runway',
        name: 'Runway ML',
        rules: [
          { type: 'domain', value: 'runwayml.com' },
          { type: 'domain', value: 'runway.com' },
          { type: 'domain', value: 'app.runwayml.com' },
          { type: 'domain', value: 'cdn.runwayml.com' },
        ],
      },
      {
        id: 'elevenlabs',
        name: 'ElevenLabs',
        rules: [
          { type: 'domain', value: 'elevenlabs.io' },
          { type: 'domain', value: 'api.elevenlabs.io' },
          { type: 'domain', value: 'cdn.elevenlabs.io' },
        ],
      },
      {
        id: 'suno',
        name: 'Suno AI (музыка)',
        rules: [
          { type: 'domain', value: 'suno.com' },
          { type: 'domain', value: 'suno.ai' },
          { type: 'domain', value: 'cdn.suno.com' },
        ],
      },
      {
        id: 'udio',
        name: 'Udio (музыка)',
        rules: [
          { type: 'domain', value: 'udio.com' },
          { type: 'domain', value: 'cdn.udio.com' },
        ],
      },
      {
        id: 'luma',
        name: 'Luma AI (Dream Machine)',
        rules: [
          { type: 'domain', value: 'lumalabs.ai' },
          { type: 'domain', value: 'dream-machine.lumalabs.ai' },
          { type: 'domain', value: 'cdn.lumalabs.ai' },
        ],
      },
      {
        id: 'kling',
        name: 'Kling AI',
        rules: [
          { type: 'domain', value: 'klingai.com' },
          { type: 'domain', value: 'cdn.klingai.com' },
        ],
      },
      {
        id: 'leonardo',
        name: 'Leonardo AI',
        rules: [
          { type: 'domain', value: 'leonardo.ai' },
          { type: 'domain', value: 'app.leonardo.ai' },
          { type: 'domain', value: 'cdn.leonardo.ai' },
        ],
      },
      {
        id: 'ideogram',
        name: 'Ideogram',
        rules: [
          { type: 'domain', value: 'ideogram.ai' },
          { type: 'domain', value: 'cdn.ideogram.ai' },
        ],
      },
      {
        id: 'adobe_firefly',
        name: 'Adobe Firefly',
        rules: [
          { type: 'domain', value: 'firefly.adobe.com' },
          { type: 'domain', value: 'firefly.adobe.io' },
          { type: 'domain', value: 'adobeautomate.io' },
        ],
      },
      {
        id: 'cohere',
        name: 'Cohere',
        rules: [
          { type: 'domain', value: 'cohere.com' },
          { type: 'domain', value: 'cohere.ai' },
          { type: 'domain', value: 'api.cohere.ai' },
        ],
      },
      {
        id: 'together',
        name: 'Together AI',
        rules: [
          { type: 'domain', value: 'together.ai' },
          { type: 'domain', value: 'together.xyz' },
          { type: 'domain', value: 'api.together.xyz' },
        ],
      },
      {
        id: 'fal',
        name: 'fal.ai',
        rules: [
          { type: 'domain', value: 'fal.ai' },
          { type: 'domain', value: 'fal.run' },
          { type: 'domain', value: 'storage.googleapis.com' },
        ],
      },
    ],
  },
  {
    id: 'education',
    label: 'Образование',
    services: [
      {
        id: 'coursera',
        name: 'Coursera',
        rules: [
          { type: 'domain', value: 'coursera.org' },
          { type: 'domain', value: 'd3njjcbhbojbot.cloudfront.net' },
          { type: 'domain', value: 'coursera-course-photos.s3.amazonaws.com' },
        ],
      },
      {
        id: 'udemy',
        name: 'Udemy',
        rules: [
          { type: 'domain', value: 'udemy.com' },
          { type: 'domain', value: 'udemycdn.com' },
          { type: 'domain', value: 'img-c.udemycdn.com' },
          { type: 'domain', value: 'udemy-images.udemy.com' },
        ],
      },
      {
        id: 'stepik',
        name: 'Stepik',
        rules: [
          { type: 'domain', value: 'stepik.org' },
          { type: 'domain', value: 'cdn.stepik.net' },
          { type: 'domain', value: 'stepik.net' },
        ],
      },
      {
        id: 'khan',
        name: 'Khan Academy',
        rules: [
          { type: 'domain', value: 'khanacademy.org' },
          { type: 'domain', value: 'cdn.kastatic.org' },
          { type: 'domain', value: 'fastly.kastatic.org' },
        ],
      },
      {
        id: 'duolingo',
        name: 'Duolingo',
        rules: [
          { type: 'domain', value: 'duolingo.com' },
          { type: 'domain', value: 'd35aaqx5ub95lt.cloudfront.net' },
          { type: 'domain', value: 'static.duolingo.com' },
        ],
      },
      {
        id: 'yandex_edu',
        name: 'Яндекс Учебник',
        rules: [
          { type: 'domain', value: 'education.yandex.ru' },
          { type: 'domain', value: 'yandex.ru' },
          { type: 'domain', value: 'yastatic.net' },
        ],
      },
      {
        id: 'practicum',
        name: 'Яндекс Практикум',
        rules: [
          { type: 'domain', value: 'practicum.yandex.ru' },
          { type: 'domain', value: 'practicum.yandex.com' },
          { type: 'domain', value: 'code.s3.yandex.net' },
          { type: 'domain', value: 'yastatic.net' },
        ],
      },
      {
        id: 'uchi_ru',
        name: 'Учи.ру',
        rules: [
          { type: 'domain', value: 'uchi.ru' },
          { type: 'domain', value: 'cdn.uchi.ru' },
          { type: 'domain', value: 'api.uchi.ru' },
        ],
      },
      {
        id: 'sberclass',
        name: 'СберКласс',
        rules: [
          { type: 'domain', value: 'sberclass.ru' },
          { type: 'domain', value: 'cdn.sberclass.ru' },
        ],
      },
      {
        id: 'resh',
        name: 'Российская электронная школа',
        rules: [
          { type: 'domain', value: 'resh.edu.ru' },
          { type: 'domain', value: 'cdn.resh.edu.ru' },
          { type: 'domain', value: 'static.resh.edu.ru' },
        ],
      },
      {
        id: 'skillbox',
        name: 'Skillbox',
        rules: [
          { type: 'domain', value: 'skillbox.ru' },
          { type: 'domain', value: 'cdn.skillbox.ru' },
          { type: 'domain', value: 'api.skillbox.ru' },
        ],
      },
      {
        id: 'geekbrains',
        name: 'GeekBrains',
        rules: [
          { type: 'domain', value: 'gb.ru' },
          { type: 'domain', value: 'geekbrains.ru' },
          { type: 'domain', value: 'cdn.gb.ru' },
        ],
      },
      {
        id: 'skyeng',
        name: 'Skyeng',
        rules: [
          { type: 'domain', value: 'skyeng.ru' },
          { type: 'domain', value: 'cdn.skyeng.ru' },
          { type: 'domain', value: 'vimeo.com' },
        ],
      },
      {
        id: 'leetcode',
        name: 'LeetCode',
        rules: [
          { type: 'domain', value: 'leetcode.com' },
          { type: 'domain', value: 'assets.leetcode.com' },
          { type: 'domain', value: 'leetcode.cn' },
        ],
      },
      {
        id: 'foxford',
        name: 'Foxford',
        rules: [
          { type: 'domain', value: 'foxford.ru' },
          { type: 'domain', value: 'cdn.foxford.ru' },
          { type: 'domain', value: 'static.foxford.ru' },
        ],
      },
      {
        id: 'sdamgia',
        name: 'СдамГИА (ЕГЭ / ОГЭ)',
        rules: [
          { type: 'domain', value: 'sdamgia.ru' },
          { type: 'domain', value: 'ege.sdamgia.ru' },
          { type: 'domain', value: 'ogz.sdamgia.ru' },
          { type: 'domain', value: 'vpr.sdamgia.ru' },
          { type: 'domain', value: 'cdn.sdamgia.ru' },
        ],
      },
      {
        id: 'reshu_ege',
        name: 'Решу ЕГЭ / ОГЭ / ВПР',
        rules: [
          { type: 'domain', value: 'reshu-ege.ru' },
          { type: 'domain', value: 'reshu-ogz.ru' },
          { type: 'domain', value: 'reshu-vpr.ru' },
          { type: 'domain', value: '5-ege.ru' },
        ],
      },
      {
        id: 'gdz_ru',
        name: 'ГДЗ.ру',
        rules: [
          { type: 'domain', value: 'gdz.ru' },
          { type: 'domain', value: 'cdn.gdz.ru' },
          { type: 'domain', value: 'static.gdz.ru' },
        ],
      },
      {
        id: 'resheba',
        name: 'Решeba / Решебник',
        rules: [
          { type: 'domain', value: 'resheba.me' },
          { type: 'domain', value: 'reshebnik.me' },
          { type: 'domain', value: 'resheba.ru' },
          { type: 'domain', value: 'reshaba.com' },
        ],
      },
      {
        id: 'gdz_net',
        name: 'ГДЗ (другие)',
        rules: [
          { type: 'domain', value: 'gdz.net' },
          { type: 'domain', value: 'gdz.lol' },
          { type: 'domain', value: 'vsegdz.com' },
          { type: 'domain', value: '4task.ru' },
          { type: 'domain', value: 'xn--d1abamebfd4afq6b8d4b.xn--p1ai' },
        ],
      },
      {
        id: 'megareshebnik',
        name: 'Мегарешебник',
        rules: [
          { type: 'domain', value: 'xn--80aefbqmhcm0d.xn--p1ai' },
          { type: 'domain', value: 'megaresheba.ru' },
        ],
      },
    ],
  },
]

export const ALL_SERVICES = SERVICE_CATEGORIES.flatMap(c => c.services)
